# Phase 1

Data exploration and cleaning

## Data exploration

In [2]:
import pandas as pd
chunks = pd.read_json("yelp_academic_dataset_review.json", lines=True, chunksize=100000)

for chunk in chunks:
    print("HEAD")
    print(chunk.head())
    print("\nCOLUMNS")
    print(chunk.columns)
    break

print("\nINFO")
for chunk in chunks:
    print(chunk.info())

HEAD
                review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw
1  BiTunyQ73aT9WBnpR9DZGw  OyoGAe7OKpv6SyGZT5g77Q  7ATYjTIgM3jUlt4UM3IypQ
2  saUsX_uimxRlCVr67Z4Jig  8g_iMtfSiwikVnbP2etR0A  YjUWPpI6HXG530lwP-fb2A
3  AqPFMleE6RsU23_auESxiA  _7bHUi9Uuf5__HHc_Q8guQ  kxX2SOes4o-D3ZQBkiMRfA
4  Sx8TMOWLNuJBWer-0pcmoA  bcjbaE6dDog4jkNY91ncLQ  e4Vwtrqf-wpJfwesgvdgxQ

   stars  useful  funny  cool  \
0      3       0      0     0
1      5       1      0     1
2      3       0      0     0
3      5       1      0     1
4      4       1      0     1

                                                text                date
0  If you decide to eat here, just be aware it is... 2018-07-07 22:09:11
1  I've taken a lot of spin classes over the year... 2012-01-03 15:28:18
2  Family diner. Had the buffet. Eclectic assortm... 2014-02-05 20:30:30
3  Wow!  Yummy, different,  delicious.   Our favo... 2015-01-04 00:01:03
4  Cute interior and owner (?) gave us tour of up... 2017-01-14 20:54:15

COLUMNS
Index(['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny',
       'cool', 'text', 'date'],
      dtype='object')

INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 100000 to 199999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 200000 to 299999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 300000 to 399999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 400000 to 499999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 500000 to 599999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 600000 to 699999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 700000 to 799999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 800000 to 899999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 900000 to 999999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1000000 to 1099999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1100000 to 1199999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1200000 to 1299999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1300000 to 1399999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1400000 to 1499999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1500000 to 1599999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1600000 to 1699999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1700000 to 1799999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1800000 to 1899999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1900000 to 1999999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2000000 to 2099999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2100000 to 2199999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2200000 to 2299999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2300000 to 2399999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2400000 to 2499999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2500000 to 2599999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2600000 to 2699999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2700000 to 2799999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2800000 to 2899999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2900000 to 2999999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64